#!/usr/bin/env python3
"""Read-only checkpoint/public-artifact scout for goal 2026-08-09.

This scout intentionally fails closed on Hugging Face access:

* no gated approval is requested;
* no test metadata/transcriptions are opened;
* no Phase-2 audio is decoded unless a candidate has already passed the
  locked strong-validation gate;
* all writes are confined to outputs/goal_2026_08_09/checkpoint_scout/.

The route metrics are imported from the existing locked validation reports.
The new exact leads were checked remotely on 2026-08-08 and are recorded as
access metadata only because their weights were not publicly downloadable.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "goal_2026_08_09" / "checkpoint_scout"


def sha256(path: Path) -> str | None:
    if not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def metric(n: int, wer: float, cer: float, zindi: float) -> dict[str, float | int]:
    return {"n": n, "wer": wer, "cer": cer, "zindi": zindi}


def delta(candidate: dict[str, Any], incumbent: dict[str, Any]) -> float:
    return float(candidate["zindi"]) - float(incumbent["zindi"])


# Public API/card observations. The card is public; the weights were not.
# `gated=manual` is the Hub API value, not an access request made by this
# script. The OmniASR API returned 401, so its private/gated/license fields
# cannot be inferred and are deliberately left unknown.
REMOTE_LEADS: list[dict[str, Any]] = [
    {
        "repo": "sulaimank/w2vbert-waxal-r2",
        "slug": "sulaimank__w2vbert-waxal-r2",
        "api_status": 200,
        "private": False,
        "gated": "manual",
        "disabled": False,
        "revision": "750c4b2c34bc56f6ed5b16b39e489226bbfa0928",
        "architecture": "Wav2Vec2BertForCTC",
        "parameters": 605750150,
        "card_language": "undeclared",
        "card_license": "undeclared",
        "card_provenance": "generic autogenerated card; dataset and evaluation are undeclared",
        "readme_status": 200,
        "weights_status": 401,
        "local_checkpoint": None,
        "validation_status": "blocked_gated_weights",
        "phase2_status": "not_decoded",
    },
    {
        "repo": "sulaimank/w2vbert-waxal-p2",
        "slug": "sulaimank__w2vbert-waxal-p2",
        "api_status": 200,
        "private": False,
        "gated": "manual",
        "disabled": False,
        "revision": "b682d9384804dcbbb98677da57bcd4875a89d893",
        "architecture": "Wav2Vec2BertForCTC",
        "parameters": 605750150,
        "card_language": "undeclared",
        "card_license": "undeclared",
        "card_provenance": "generic autogenerated card; dataset and evaluation are undeclared",
        "readme_status": 200,
        "weights_status": 401,
        "local_checkpoint": None,
        "validation_status": "blocked_gated_weights",
        "phase2_status": "not_decoded",
    },
    {
        "repo": "sulaimank/w2vbert-waxal-p2b",
        "slug": "sulaimank__w2vbert-waxal-p2b",
        "api_status": 200,
        "private": False,
        "gated": "manual",
        "disabled": False,
        "revision": "c32f9ea7d7939a2280c7be8dd493c3e9b6c1c012",
        "architecture": "Wav2Vec2BertForCTC",
        "parameters": 605750150,
        "card_language": "ach, mas, nyn (card-only claims; no lin/lug/sna claim)",
        "card_license": "undeclared",
        "card_provenance": "trained from scratch on None; card reports Ach/Mas/Nyn only",
        "card_metrics": {
            "ach": {"wer": 0.3353, "cer": 0.1347, "zindi": 0.7650},
            "mas": {"wer": 0.5025, "cer": 0.1108, "zindi": 0.6934},
            "nyn": {"wer": 0.3598, "cer": 0.0849, "zindi": 0.7777},
        },
        "readme_status": 200,
        "weights_status": 401,
        "local_checkpoint": None,
        "validation_status": "blocked_gated_weights",
        "phase2_status": "not_decoded",
    },
    {
        "repo": "sulaimank/w2vbert-waxal-multi7",
        "slug": "sulaimank__w2vbert-waxal-multi7",
        "api_status": 200,
        "private": False,
        "gated": "manual",
        "disabled": False,
        "revision": "2c13f967ed9b16675571c5b713d42685873f2b07",
        "architecture": "Wav2Vec2BertForCTC",
        "parameters": 605750150,
        "card_language": "ach, lin, lug, mas, nyn, sna, sog (card-only claims)",
        "card_license": "undeclared",
        "card_provenance": "fine-tuned from sulaimank/w2v-bert-waxal on None",
        "card_metrics": {
            "ach": {"wer": 0.3978, "cer": 0.1490, "zindi": 0.7266},
            "lin": {"wer": 0.2111, "cer": 0.0937, "zindi": 0.8476},
            "lug": {"wer": 0.2779, "cer": 0.0440, "zindi": 0.8390},
            "nyn": {"wer": 0.4323, "cer": 0.0928, "zindi": 0.7375},
            "sna": {"wer": 0.3840, "cer": 0.0976, "zindi": 0.7592},
            "sog": {"wer": 0.5612, "cer": 0.1014, "zindi": 0.6687},
        },
        "readme_status": 200,
        "weights_status": 401,
        "local_checkpoint": None,
        "validation_status": "blocked_gated_weights",
        "phase2_status": "not_decoded",
    },
    {
        "repo": "sulaimank/omniASR-CTC-300M-waxal",
        "slug": "sulaimank__omniASR-CTC-300M-waxal",
        "api_status": 401,
        "private": "unknown",
        "gated": "unknown",
        "disabled": "unknown",
        "revision": None,
        "architecture": "unknown without authorized metadata",
        "parameters": None,
        "card_language": "Lingala, Ganda, Shona (public search-index claim only)",
        "card_license": "unknown without authorized metadata",
        "card_provenance": "public search index exposed an ASR model-tree page; direct API/card/weights returned 401",
        "readme_status": 401,
        "weights_status": 401,
        "local_checkpoint": None,
        "validation_status": "blocked_unauthorized",
        "phase2_status": "not_decoded",
    },
]


def checkpoint_inventory() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for config in sorted((ROOT / "checkpoints").rglob("config.json")):
        model = config.parent / "model.safetensors"
        if not model.is_file():
            continue
        rows.append(
            {
                "path": str(config.parent.relative_to(ROOT)),
                "config_sha256": sha256(config),
                "model_size_bytes": model.stat().st_size,
                "model_sha256": None,
                "model_hash_status": "not_rehashed_in_scout_156GB_checkpoint_tree",
            }
        )
    return rows


def artifact_hashes() -> dict[str, Any]:
    paths = [
        "outputs/goal_2026_08_07/badrex_tiers/submission_phase2_badrex_sna_sim99_lug_splitjoin.csv",
        "outputs/goal_2026_08_08/sulaiman_public_descendants/phase2_cache_w2vbert-lingala-sd3.csv",
        "outputs/goal_2026_08_08/sulaiman_public_descendants/phase2_cache_whisper-small-lingala-cased-2.csv",
        "outputs/goal_2026_08_08/shona_sd2_parallel/phase2_cache_w2vbert-shona-sd2.csv",
        "outputs/goal_2026_08_08/sunbird51_nyn_seed42_n120/nyn_hyps.csv",
        "outputs/goal_2026_08_08/sunbird51_routes_full/lug_hyps.csv",
        "outputs/goal_2026_08_08/hidden_routes/private_safe_replacements.csv",
        "outputs/goal_2026_08_08/hidden_routes/sog_same_id.csv",
    ]
    return {
        path: {"sha256": sha256(ROOT / path), "exists": (ROOT / path).is_file()}
        for path in paths
    }


def route_comparison() -> dict[str, Any]:
    # All metrics below are from existing validation-only reports; no labels
    # are loaded by this scout. The raw/case-sensitive scoring caveat is kept
    # in the report and no normalized replacement text is generated here.
    return {
        "protocol": {
            "sample_seed": 42,
            "strong_gate": "candidate delta_zindi>=0.01, lower WER, positive tune and holdout deltas, paired-bootstrap p05 delta>0",
            "normalization": "existing reports use src.text_norm.normalize_text; raw case/punctuation artifacts remain untouched",
            "test_labels_used": False,
            "phase2_decoded_by_this_scout": False,
        },
        "routes": {
            "lin": {
                "validation": "seed42 n=80",
                "incumbent": metric(80, 0.3023469857340083, 0.13055272973889454, 0.7835501422635486),
                "candidate": "existing public sulaimank/w2vbert-lingala-sd3",
                "candidate_metric": metric(80, 0.08191440404970088, 0.05272973889454052, 0.9326779285278793),
                "delta_zindi": 0.14912778626433076,
                "strong_pass": True,
                "cache_hash": "808cc40725c86775a711cd23c1947ddd44a72ecb24c1fa6ee695e8a5cb6abd92",
                "note": "existing pass/context only; none of the five new leads was decoded",
            },
            "lug": {
                "validation": "corrected seed42 n=40 plus independent seed42 n=150 check",
                "incumbent": metric(40, 0.20517097581317764, 0.04221082089552239, 0.87630910164565),
                "candidate": "local mms_ft_v4_standard_beam_splitjoin",
                "candidate_metric": metric(40, 0.16263552960800667, 0.03661380597014925, 0.900375332210922),
                "delta_zindi": 0.024066230565272018,
                "strong_pass": False,
                "cache_hash": "aa67f2f8c03cfa09859ee5588365c7b9485e927e0563909aaee58920f1035585",
                "note": "proxy gain failed deployment/public-transfer gate; independent n=150 mms_ft_v5b zindi 0.8830628168 vs incumbent 0.8836723143",
            },
            "nyn": {
                "validation": "seed42 n=120",
                "incumbent": metric(120, 0.394919972164231, 0.10365659777424484, 0.7507117150307621),
                "candidate": "existing Sunbird route",
                "candidate_metric": metric(120, 0.32950591510090466, 0.10329320917556212, 0.7836004378617666),
                "delta_zindi": 0.0328887228310045,
                "strong_pass": False,
                "cache_hash": "54c2a4ce3c99890bad669ee3c7c453ba148ef64fc1beb3c476b953b679dfc8ff",
                "note": "nested speaker-CV selector reaches 0.7912988329 but is an existing selector diagnostic, not a new lead",
            },
            "ach": {
                "validation": "seed42 n=120",
                "incumbent": metric(120, 0.3287009063444109, 0.1350292699724518, 0.7681349118415687),
                "candidate": "local waxal-ach-salt-mix-v2",
                "candidate_metric": metric(120, 0.3969788519637462, 0.14161501377410468, 0.7307030671310746),
                "delta_zindi": -0.0374318447104941,
                "strong_pass": False,
                "cache_hash": None,
                "note": "LM-head alternative is also below incumbent; no new exact lead was accessible",
            },
            "sna": {
                "validation": "corrected seed42 n=120",
                "incumbent": metric(120, 0.19952114924181963, 0.0652087868592915, 0.8676350319494445),
                "candidate": "existing Manasseh w2v-bert Shona",
                "candidate_metric": metric(120, 0.21468475658419792, 0.07104690283000198, 0.8571341702929001),
                "delta_zindi": -0.0105008616565444,
                "strong_pass": False,
                "cache_hash": None,
                "note": "raw case/punctuation scoring audit recommends preserving raw specialist outputs; no raw rewrite was performed",
            },
            "sog": {
                "validation": "WAXAL proxy seed42 n=40",
                "incumbent": metric(40, 0.5130597014925373, 0.1055052076288381, 0.6907175454393123),
                "candidate": "existing Sunbird Soga route",
                "candidate_metric": metric(40, 0.4766791044776119, 0.11199783579061275, 0.7056615298658877),
                "delta_zindi": 0.014943984426575407,
                "strong_pass": False,
                "cache_hash": "d1e52df06e2ea0248d2b284f2b4f5b3d27a4ff9bfdc47d4d974b81fc760e03ca",
                "note": "not deployable: the old route has one Sog-sensitive row and MMS-LID language identity is uncertain",
            },
            "luo_detector_context": {
                "validation": "Google FLEURS luo_ke seed42 n=80",
                "incumbent": metric(80, 0.23722431414739106, 0.0526367475203771, 0.8550694691661159),
                "candidate": "existing CLEAR-Luo witness",
                "candidate_metric": metric(80, 0.26627218934911245, 0.05872532652459982, 0.8375012420631438),
                "delta_zindi": -0.01756822710297277,
                "strong_pass": False,
                "cache_hash": "c70fc94ce2d702e323ec3ef803e4c5c3b9e1ec3e8a4ad7c7ed7ac76fac144f9b",
                "note": "Luo is detector/residual context, not a WAXAL target language; no new lead decoded",
            },
        },
    }


def write_outputs() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for lead in REMOTE_LEADS:
        path = OUT / lead["slug"]
        path.mkdir(parents=True, exist_ok=True)
        payload = {
            "repo": lead,
            "access_rule": "No gated approval requested; no weight download attempted after 401/gated status.",
            "validation": {"decoded": False, "reason": lead["validation_status"]},
            "phase2": {"decoded": False, "reason": "strong validation gate not reached"},
        }
        (path / "access.json").write_text(json.dumps(payload, indent=2) + "\n")

    inventory = {
        "checkpoint_root": str(ROOT / "checkpoints"),
        "checkpoint_count_with_config_and_weights": len(checkpoint_inventory()),
        "model_hash_policy": "config files hashed; 156GB model tree not fully rehashed; selected evaluated artifact hashes are recorded separately",
        "checkpoints": checkpoint_inventory(),
        "artifacts": artifact_hashes(),
    }
    (OUT / "inventory.json").write_text(json.dumps(inventory, indent=2) + "\n")

    comparison = route_comparison()
    (OUT / "route_comparison.json").write_text(json.dumps(comparison, indent=2) + "\n")

    blocked = [lead["repo"] for lead in REMOTE_LEADS if not lead["validation_status"].startswith("validated")]
    report = [
        "# Checkpoint scout — goal 2026-08-09",
        "",
        "Date: 2026-08-08. Scope is read-only. Existing files were not modified.",
        "",
        "## Decision",
        "",
        "No new lead was eligible for locked validation. The four W2V-BERT repos are `private=false` but `gated=manual`; public README/card access does not make `model.safetensors` downloadable, and each weight request returned HTTP 401. `sulaimank/omniASR-CTC-300M-waxal` returned HTTP 401 for API metadata, README, and weights. No new gated approval was requested, no weights were downloaded, and no Phase2 route was decoded.",
        "",
        "## Exact lead access audit",
        "",
        "| Repo | API | Gated/private | Coverage signal | License | Weights | Validation | Phase2 |",
        "|---|---:|---|---|---|---:|---|---|",
    ]
    for lead in REMOTE_LEADS:
        report.append(
            f"| `{lead['repo']}` | {lead['api_status']} | `{lead['gated']}` / `{lead['private']}` | {lead['card_language']} | {lead['card_license']} | {lead['weights_status']} | {lead['validation_status']} | {lead['phase2_status']} |"
        )
    report += [
        "",
        "The p2b and multi7 card metrics are card-only claims, not locked-sample measurements. They were not used for route selection. r2 and p2 cards do not declare language, data, evaluation, or license. There is no local checkpoint for any of the five exact repo names.",
        "",
        "## Locked route comparison",
        "",
        "Metrics below are exact values imported from existing validation-only reports. `delta_zindi` is candidate minus incumbent on the same locked sample. A `strong_pass` is only true when the existing report’s full gate passed; a positive proxy delta alone is not promoted.",
        "",
        "| Route | n/protocol | Incumbent Zindi | Existing best/context Zindi | Delta | Strong pass |",
        "|---|---|---:|---:|---:|---|",
    ]
    for route, row in comparison["routes"].items():
        inc = row["incumbent"]["zindi"]
        cand = row["candidate_metric"]["zindi"]
        report.append(
            f"| `{route}` | {row['validation']} | {inc:.10f} | {cand:.10f} | {float(row['delta_zindi']):+.10f} | {'YES' if row['strong_pass'] else 'NO'} |"
        )
    report += [
        "",
        "Key route findings:",
        "",
        "- Luganda: local `mms_ft_v4_standard_beam_splitjoin` is +0.0240662306 on corrected n=40, but the independent n=150 check has `mms_ft_v5b` at 0.8830628168 versus the 0.8836723143 incumbent; the deployment/public-transfer gate remains failed.",
        "- Nyanja: the existing Sunbird route is +0.0328887228 on n=120; the nested speaker-CV selector diagnostic reaches 0.7912988329, but neither is a new lead from this scout.",
        "- Acholi: the existing WAXAL specialist remains incumbent; SALT mix is -0.0374318447 and the LM-head alternative is also below floor.",
        "- Soga: Sunbird is +0.0149439844 on a n=40 proxy, but language identity and one-row deployment geometry prevent promotion.",
        "- Luo: the existing MMS-1B detector context remains stronger than the CLEAR witness by 0.0175682271 Zindi on FLEURS; it is not a WAXAL target-language route.",
        "",
        "## Cache and artifact hashes",
        "",
        "The complete machine-readable inventory and hashes are in `inventory.json`; selected route comparison hashes are in `route_comparison.json`. The current 2,392-row Phase2 spine hash is `fef4f8cf9042a054ff7b5c11d3f7aa1161882c38a84ba33d44ffbab767d4ba32`. Existing public cache hashes include Lingala W2V `808cc40725c86775a711cd23c1947ddd44a72ecb24c1fa6ee695e8a5cb6abd92`, Lingala Whisper `a3e01ce4bcb159da25aeb93b889937f58a621f6b83f015f9ef78d0a7470bb09f`, Shona SD2 `29f27b0d53e3d57c3a461990f257c96ac3b2844bbab8c193492955287b50500e`, and Nyanja Sunbird `54c2a4ce3c99890bad669ee3c7c453ba148ef64fc1beb3c476b953b679dfc8ff`.",
        "",
        "For the five new leads, cache hash is `none`: no model weight entered the local cache. The repository commit SHA is recorded per model where the unauthenticated API exposed it.",
        "",
        "## Compliance",
        "",
        "- Test labels/transcriptions: not read by this scout.",
        "- Raw case/punctuation: no hypotheses were rewritten; the prior scoring-forensics recommendation to retain raw specialist text remains in force.",
        "- Phase2: no new route was decoded because no candidate passed the strong validation gate.",
        "- Writes: only this directory and the explicitly allowed scout script were written.",
    ]
    (OUT / "scout_report.md").write_text("\n".join(report) + "\n")

    manifest = {
        "goal": "2026-08-09 checkpoint scout",
        "script": str(Path(__file__).relative_to(ROOT)),
        "new_leads": [lead["repo"] for lead in REMOTE_LEADS],
        "blocked_leads": blocked,
        "validated_new_leads": [],
        "phase2_decoded": [],
        "test_labels_used": False,
        "writes_confined_to": str(OUT.relative_to(ROOT)),
    }
    (OUT / "run_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    write_outputs()
    print(json.dumps({"output": str(OUT), "new_validated_leads": []}, indent=2))
